### ISSUE TITLE
Error when transforming some test documents

### ISSUE THREAD

**Issue by charlie-ablett** [ottoville/DOCX2HTML.XSL#4]
Hi there, I'm using Saxon HE via the Java JVM and using docx2html.

I've got errors logged in [this gist](https://gist.github.com/charlie-ablett/63b1b8f70a04b0074c5cb99acd35c49c).

Any help appreciated!

[test-1.docx](https://github.com/ottoville/DOCX2HTML.XSL/files/251379/test-1.docx)
[demo.docx](https://github.com/ottoville/DOCX2HTML.XSL/files/251369/demo.docx)

**Comment by charlie-ablett** [comment]
If I can get the document working with the js or c version, I might chalk it up to an error with the jar. Here's a similar error: https://saxonica.plan.io/boards/2/topics/6006

**Comment by ottoville** [comment]
Hello Charlie

Thank you for contributing. I was able to track down these errors and got them fixed on latest version.
https://github.com/ottoville/DOCX2HTML.XSL/archive/master.zip

However I noticed that document you supplied are not formatted as good as they should, I will keep working on that.

**Comment by charlie-ablett** [comment]
Thank you! :)

**Comment by ottoville** [comment]
Now detection of pages has been improved to show pages correct in test document that you provided.
https://github.com/ottoville/DOCX2HTML.XSL/archive/master.zip
As the original error has been fixed I will close this ticket now. If there is something else you would like to get fixed in your test document please file new tickets.
